#!/usr/bin/env zsh

[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

alias bn="bun"
alias bnc="bun create"
alias bnb="bun run build"
alias bnd="bun run dev"
alias bndp="bun run deploy"
alias bnft="bun run format"
alias bnin="bun i"
alias bnind="bun i -D "
alias bning="bun i -g"
alias bnls="bun list"
alias bnlsg="bun list -g"
alias bnlt="bun run lint"
alias bnltf="bun run lint -- --fix"
alias bnr="bun run"
alias bns="bun run serve"
alias bnstt="bun start"
alias bnt="bun test"
alias bnun="bun uninstall"
alias bnung="bun -g uninstall"
alias bnx="bunx"
