#!/usr/bin/env zsh

[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

alias bun="bun"
alias bunc="bun create"
alias bunb="bun run build"
alias bund="bun run dev"
alias bundp="bun run deploy"
alias bunft="bun run format"
alias bunin="bun i"
alias bunind="bun i -D "
alias buning="bun i -g"
alias bunls="bun list"
alias bunlsg="bun list -g"
alias bunlt="bun run lint"
alias bunltf="bun run lint -- --fix"
alias bunr="bun run"
alias buns="bun run serve"
alias bunstt="bun start"
alias bunt="bun test"
alias bunun="bun uninstall"
alias bunung="bun -g uninstall"
alias bunx="bunx"
