#!/usr/bin/env zsh

[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

alias bun="bun"
alias bunc="bun create"
alias bunb="bun run build"
alias bund="bun run dev"
alias bundp="bun run deploy"
alias bunf="bun run format"
alias buni="bun i"
alias bunid="bun i -D"
alias bunig="bun i -g"
alias bunl="bun run lint"
alias bunls="bun list"
alias bunlsg="bun list -g"
alias bunl="bun run lint"
alias bunlf="bun run lint -- --fix"
alias bunr="bun run"
alias buns="bun start"
alias bunt="bun test"
alias bunu="bun uninstall"
alias bunug="bun -g uninstall"
