#!/usr/bin/env zsh

alias ac_="appcode"
alias qa_="aqua"
alias cl_="clion"
alias dg_="datagrip"
alias ds_="datagrip"
alias go_="goland"
alias ij_="intelij"
alias ps_="phpstorm"
alias pc_="pycharm"
alias rd_="rider"
alias rm_="rubymine"
alias rr_="rustrover"
alias ws_="webstorm"
alias space="open -a 'Space Desktop'"
