#!/usr/bin/env zsh

alias nb="nr build"
alias nc="pnpm create"
alias nd="nr dev"
alias nf="nr format"
alias nid="ni -D"
alias nit="pnpm init"
alias nig="ni -g"
alias nl="nr lint"
alias nlf="nr lint --fix"
alias nlff="nr lint --fix && nr format"
alias ns="nr start"
alias nt="nr test"
alias nug="nu -g"
alias nx="nlx"
