#!/usr/bin/env zsh

alias npmc="npm create"
alias npmb="npm run build"
alias npmd="npm run dev"
alias npmdp="npm run deploy"
alias npmf="npm run format"
alias npmi="npm i"
alias npmid="npm i -D"
alias npmig="npm i -g"
alias npmls="npm list"
alias npmlsg="npm list -g"
alias npml="npm run lint"
alias npmlf="npm run lint -- --fix"
alias npmr="npm run"
alias npms="npm start"
alias npmt="npm test"
alias npmu="npm uninstall"
alias npmug="npm -g uninstall"
