#!/usr/bin/env zsh

alias n="npm"
alias nc="npm create"
alias nb="npm run build"
alias nd="npm run dev"
alias ndp="npm run deploy"
alias nft="npm run format"
alias nin="npm i"
alias nind="npm i -D "
alias ning="npm i -g"
alias nls="npm list"
alias nlsg="npm list -g"
alias nlt="npm run lint"
alias nltf="npm run lint -- --fix"
alias nr="npm run"
alias ns="npm run serve"
alias nstt="npm start"
alias nt="npm test"
alias nun="npm uninstall"
alias nung="npm -g uninstall"
alias nx="npx"
