#!/usr/bin/env zsh

alias npc='npm create'
alias npb='npm run build'
alias npd='npm run dev'
alias npdp='npm run deploy'
alias npf='npm run format'
alias npi='npm i'
alias npid='npm i -D'
alias npig='npm i -g'
alias npl='npm run lint'
alias nplf='npm run lint -- --fix'
alias nplff='npm run lint -- --fix && npm run format'
alias npls='npm list'
alias nplsg='npm list -g'
alias npr='npm run'
alias nps='npm start'
alias npt='npm test'
alias npu='npm uninstall'
alias npug='npm -g uninstall'
