#!/usr/bin/env zsh

PACKAGE="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Configs/zsh/package"

source "$PACKAGE/general.zsh"
source "$PACKAGE/directory.zsh"
source "$PACKAGE/artisan.zsh"
source "$PACKAGE/brew.zsh"
source "$PACKAGE/bun.zsh"
source "$PACKAGE/clamav.zsh"
source "$PACKAGE/composer.zsh"
source "$PACKAGE/complement.zsh"
source "$PACKAGE/docker.zsh"
source "$PACKAGE/fig.zsh"
source "$PACKAGE/gcloud.zsh"
source "$PACKAGE/gh.zsh"
 source "$PACKAGE/haskell.zsh"
source "$PACKAGE/jetbrains.zsh"
source "$PACKAGE/npm.zsh"
source "$PACKAGE/pnpm.zsh"
source "$PACKAGE/ruby.zsh"
source "$PACKAGE/sail.zsh"
source "$PACKAGE/volta.zsh"
source "$PACKAGE/work.zsh"
