#!/usr/bin/env zsh

alias pn="pnpm"
alias pnc="pnpm create"
alias pnb="pnpm run build"
alias pnd="pnpm run dev"
alias pndp="pnpm run deploy"
alias pnft="pnpm run format"
alias pnin="pnpm i"
alias pnind="pnpm i -D "
alias pning="pnpm i -g"
alias pnls="pnpm list"
alias pnlsg="pnpm list -g"
alias pnlt="pnpm run lint"
alias pnltf="pnpm run lint -- --fix"
alias pnr="pnpm run"
alias pns="pnpm run serve"
alias pnstt="pnpm start"
alias pnt="pnpm test"
alias pnun="pnpm uninstall"
alias pnung="pnpm -g uninstall"
alias pnx="pnpx"
